backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "prices" # Used in routes, e.g., /admin/collections/blog
    label: "Prices" # Used in the UI
    type: "prices"
    folder: "content/prices" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "prices" }
      - { label: "Type", name: "type", widget: "hidden", default: "prices" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "tags", widget: "list", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
